baseURL = "https://www.techbozeman.com"
languageCode = "en-us"
title = "Tech Bozeman"
theme = "hyalite"

[params]
  subtitle = "Tech Companies in Bozeman, MT"
  description = "Tech Bozeman provides news and information about Bozeman, Montana tech companies, groups, events, jobs, and coworking."
  twitter = "techbozeman"
  github = "beaorn/techbozeman"
  google_site_verification = "8gqkTMHftpoGnc1k1Oo2x-eNktjJMsjDEbEYKkYSQEw"
  matomo_baseurl = "stats.agrinux.com"
  matomo_siteid = "5"
